server_url = "0.0.0.0:4244"
deeppavlov_url = "http://deeppavlov:5555//model"
mongodb_url = "mongodb://mongodb_newsplatform:27017"
database_name = "news"
cards_collection_name = "news"
sources_collection_name = "sources"
tags_collection_name = "tags"
queries_cache_size = 100
exact_card_cache_size = 1000