version: "3"

services:
    mongodb_newsplatform:
        command: mongod
        image: mongo:4.4
        container_name: "mongodb_newsplatform"
        restart: always
        # ports:
        #     - 127.0.0.1:27042:27017
        expose:
            - "27017"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./mongo-volume:/data/db

    newsplatform:
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./Config.toml:/newsplatform/Config.toml
            - ./run.sh:/newsplatform/run.sh
            - ./news_parser/text2wikititle:/newsplatform/text2wikititle
        ports:
            - 127.0.0.1:2086:2086
            - 127.0.0.1:2087:2087
        links:
            - mongodb_newsplatform
        depends_on:
            - mongodb_newsplatform
