version: "3"

services:
    mongodb:
        command: mongod
        image: mongo:4.4
        container_name: "mongodb"
        ports:
            - 127.0.0.1:27017:27017
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./mongo-volume:/data/db

    # deeppavlov:
    #     image: deeppavlov/base-cpu:latest
    #     container_name: "deeppavlov"
    #     ports:
    #         - 127.0.0.1:5555:5000
    #     volumes:
    #         - ./dp_components:/root/.deeppavlov
    #     environment:
    #         - CONFIG=ner_ontonotes_bert_mult

    newsplatform:
        build:
            context: .
            dockerfile: ./Dockerfile
        # working_dir: /newsplatform/
        # command: ./newsplatform/run.sh
        volumes:
            - ./configs:/newsplatform/configs
        depends_on:
            - mongodb
            # - deeppavlov
